### ISSUE TITLE
Jetson TX2 CUDA TOOLKIT ROOT DIR Error

### ISSUE THREAD

**Issue by odobenuskr** [odobenuskr/2019_Capstone_FlexAds#5]
Jetson TX2 를 TX1 과 동일하게 세팅한 다음, Jetson-Inference 깃의 튜토리얼을 진행하던 중

jetson-inference/build 디렉토리에서 cmake ../ 명령어를 쳤을 때 다음과 같은 에러가 발생하였습니다.

CUDA_TOOLKIT_ROOT_DIR not found or specified 

그 이후, make 를 통해 다양한 camera / console 프로그램을 build 하는 과정에서 makefile 이 존재하지 않아 문제가 생깁니다.

이에 대한 근본적 해결책은 CUDA TOOLKIT 의 디렉토리를 확인하고 cmake 명령어를 에러 없이 실행시키는 것입니다.

**Comment by odobenuskr** [comment]
https://github.com/dusty-nv/jetson-inference/issues/79

여기에 해결법이 있을지도 모를 것 같음

**Comment by HSOOJ** [comment]
error content

**Comment by odobenuskr** [comment]
Jetpack 의 설치 과정에서 CUDA-Toolkit 을 TX2 내부에서 sudo apt-get install cuda-toolkit-9-0 으로 수동설치하는 것으로 해결 완료. 초기에도 동일한 수동 설치가 이루어졌음에도 작동하지 않았던 이유는 정확하게 밝혀내지 못함.
